### ISSUE TITLE
i18n : fix english original string in readme.txt

### ISSUE THREAD

**Issue by audrasjb** [audrasjb/gdpr-data-request-form#5]
Replace
`The personal data are sent by email to the user/visitor (as a 3-day download link), or erased, depending of the user request type.`
With
`The personal data are sent by email to the user/visitor (as a 3-day available download link), or erased, depending on the user request type.`

Submitted by @presskopp in Make WordPress Slack.

**Comment by abdullah1908** [comment]
I am taking it and submit PR soon.

**Comment by audrasjb** [comment]
Fixed with #13 
Props @Presskopp
