### ISSUE TITLE
Fix an error in readme.txt file / Location of user requests

### ISSUE THREAD

**Issue by audrasjb** [audrasjb/gdpr-data-request-form#6]
This string in your GDPR Plugin:
`The user request is set to Confirmed in WordPress Admin &gt; Settings &gt; Privacy.`
seems wrong to me.
It is to find under `Tools > export/erase personal data`

Submitted by @presskopp in Make WordPress Slack.

**Comment by abdullah1908** [comment]
I am taking it as well.

**Comment by audrasjb** [comment]
Fixed in #8 
Thanks @abdullah1908

**Comment by audrasjb** [comment]
Reopening since #8 is not completely fixing this issue, this is also present in the plugin’s FAQ.

**Comment by audrasjb** [comment]
Fixed in #10
